app:
  name: todo-app
  version: v1.0.0
  host: 127.0.0.1
  port: 8080

controller:
  path: internal/controllers

model:
  path: internal/models

supabase:
  target: self-hosted # options is self-hosted or cloud, default value is local
  url: http://localhost:8000

  # cloud config
  account:

  # self-hosted config
  workloadManagement: docker-compose # options is docker-compose or kubernetes, default value is docker-compose
  secret:
    jwt:
      secret: your jwt secret
      serviceKey: your service key
      anonKey: your anon key
      expiry: 3600
    basic:
      username: supabase
      password: s3cr3t
    database:
      host: localhost
      username: postgres
      password: postgres
      database: postgres
      port: 5432
  resources:
    auth:
      enable: true
    rest:
      enable: true
    meta:
      enable: true
      basePath: /api/pg-meta/default
    realtime:
      enable: false
    storage:
      enable: false
