PROJECT_NAME: todo-app
DEPLOYMENT_TARGET: self_hosted
CLOUD_ACCESS_TOKEN: 

SUPABASE_API_URL: http://localhost:54323
SUPABASE_API_BASE_PATH: /api/pg-meta/default
SUPABASE_REST_URL: 

SERVER_HOST: 127.0.01
SERVER_PORT: 8002
