PROJECT_NAME: trace-app
GO_MODULE_NAME: trace-app
DEPLOYMENT_TARGET: self_hosted

SUPABASE_API_URL: http://localhost:54323
SUPABASE_API_BASE_PATH: /api/pg-meta/default

TRACE_ENABLE: true
TRACE_ENDPOINT: localhost:4317
TRACE_COLLECTOR: otpl

SERVER_HOST: 127.0.01
SERVER_PORT: 8002
